#!/usr/bin/env zsh

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Set prompt
PS1=$'${(e)$(prompt_paradox_build_prompt)}\n ${editor_info[keymap]} '

#PS1=`sed "/^$/d" <<< "$PS1"`
# Print a random, hopefully interesting, adage.
# if (( $+commands[fortune] )); then
#   if [[ -t 0 || -t 1 ]]; then
#     fortune -s
#     print
#   fi
# fi
