#!/usr/bin/env zsh
# Executes commands at login pre-zshrc.

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Set the list of directories that Zsh searches for programs.
path=(
"$HOME/perl5/bin"
"$HOME/.rbenv/bin"

/usr/local/{bin,sbin}
/usr/libexec
"$path[@]"
/Users/ryan/.gem/ruby/2.0.0/bin
)
# "$HOME/.rbenv/versions/$(rbenv version-name)/bin"
# ~/.fzf/bin

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Configure to acccess the Zsh help pages
  unalias run-help &> /dev/null
  autoload run-help
  HELPDIR=/usr/local/share/zsh/help


# Fink initialization
#. /sw/bin/init.sh
# Set path for Mac Ports
#export MANPATH=/opt/local/share/man:$MANPATH

# Configure to acccess the Zsh help pages
  unalias run-help &> /dev/null
  autoload run-help
  HELPDIR=/usr/local/share/zsh/help

# Fink initialization
#. /sw/bin/init.sh

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# Define lessc formula
 lessc () { vim -u /usr/share/vim/vim74/macros/less.vim "$@" }
