#!/usr/bin/env zsh
# Executes commands at login pre-zshrc.
echo '~zprofile'
#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='micro'
export VISUAL='mvim --remote-tab'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set path for Mac Ports
#export MANPATH=/opt/local/share/man:$MANPATH

# Configure to acccess the Zsh help pages
  unalias run-help &> /dev/null
  autoload run-help
  HELPDIR=/usr/local/share/zsh/help

# Set path for Mac Ports
#export MANPATH=/opt/local/share/man:$MANPATH

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -S -w -z-4'

#
# Temporary Files
#
#
if [[ -z "$TMPDIR" ]]; then
  export TMPDIR="/tmp/zsh-$UID"
fi

if [[ ! -d "$TMPDIR" ]]; then
  mkdir "$TMPDIR"
  chmod 700 "$TMPDIR"
fi

# Set prompt
#PS1=$'${(e)$(prompt_paradox_build_prompt)}\n ${editor_info[keymap]} '

# Define lessc formula
 lessc () { vim -u /usr/share/vim/vim74/macros/less.vim "$@" }
