#!/usr/bin/env zsh
# Defines environment variables.
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath path mailpath

setopt extended_glob

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
## Perl
#

# perlbrew initialization

# Append the following piece of code to the end of your ~/.zshenv and start a new shell, perlbrew should be up and fully functional from there:
source ~/perl5/perlbrew/etc/bashrc

# Set the list of directories that Zsh searches for programs.
path=("${(f)$(< /etc/paths < /etc/paths.d/*)}")
path=(
"$HOME/bin"
/usr/{local/,}{bin,sbin}
"$path[@]"
)
