#!/usr/bin/env zsh
# Executes commands at the start of an interactive session.

zmodload zsh/zprof
local zshrc_start=$(gdate +%s%N)

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

zmodload zsh/zprof
local zshrc_start=$(gdate +%s%N)

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
# Source Prezto.
if [[ -s "/Users/ryan/.zprezto/init.zsh" ]]; then
  source "/Users/ryan/.zprezto/init.zsh"
fi

# Fuzzy Completions
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# F path to completion functions
fpath=(
/usr/local/share/zsh/site-functions
/usr/local/Homebrew/completions
"$fpath[@]"
/usr/local/var/homebrew/linked/zsh/share/zsh/functions
)

# gulp
# eval "$(gulp --completion=zsh)"

# Personalizations
alias rhelp=run-help
alias gi='grep -i'
export CLICOLOR=xterm-color
export PIP_FORMAT=columns
alias getmyip='dig +short myip.opendns.com @resolver1.opendns.com'
function copy-kill-whole-line {
  zle kill-whole-line
  echo -n $CUTBUFFER | pbcopy
}
# set working dir to path of top Finder window
alias fd="$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
alias netports="networksetup -listallhardwareports"
# youtube-dl
alias yt=youtube-dl
alias yta='youtube-dl -x --audio-format best --audio-quality 0'
alias ytv='youtube-dl --output /Volumes/attic/YouTube\ Video\ Library/%(title)s.%(etc)s'
alias ytp='youtube-dl --output /Volumes/attic/electronics/%(title)s.%(etc)s'
alias openssl-brew='/usr/local/opt/openssl/bin/openssl'
export GOPATH="$(go env GOPATH)"
# Homebrew
# brewO() {brewI --json=v1 "$1" |jq -j '.[]| .installed[-1].used_options | join(" ")'}
brewI2C() {
  local installed=(${(Fo)$(brewO "$1")#*with-})
  local current=("${(f)$(brew options "$1" | sed -E -e '/^--with-/!d' -e 's/^--with-(.*)/\1/')}")
  /usr/bin/diff =(print -l -- $installed) =(print -l -- $current)
}
# Brew options installed
brewO() {brewI --json=v1 "$1" |jq -j '.[]| .installed[-1].used_options | join(" ")'}
alias pipi="CFLAGS=-I$(brew --prefix)/include LDFLAGS=-L$(brew --prefix)/lib pip install $@"
# Brew install all options (for the frequent case of all options except "without" options; Meant to improve efficiency, not replace manual review
function brewAllo () {                                                                                [09:52:30]
    export _brewAllo_param="$1"
    local opts=(${$(brew options --compact $_brewAllo_param)//--without*/})
    print -l -- "$opts[@]"
    brew install "$1" "$opts[@]"
    print "num opts: $#opts"
    print -- "args passed: $*"
}
# zmodload for modules with parameters
zmodload -F zsh/stat b:zstat

# # Node version manager
 export NVM_LAZY_LOAD=true
 source "$HOME/.nvm/zsh-nvm/zsh-nvm.plugin.zsh"

# perl : By default non-brewed cpan modules are installed to the Cellar. If you wish for your modules to persist across updates we recommend using `local::lib`.
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
cpanm local::lib 2>&1 > "$TMPDIR/cpan-load_${$(gtty)##*/}.log"
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

# iTerm2 shell integration hooks
source ~/.iterm2_shell_integration.zsh

# Node version manager
# place this after nvm initialization!
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" != "N/A" ] && [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm install
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc
gdate "+s%N"

# # Node version manager
 export NVM_LAZY_LOAD=true
 source "/Users/ryan/.nvm/zsh-nvm/zsh-nvm.plugin.zsh"

# perl : By default non-brewed cpan modules are installed to the Cellar. If you wish for your modules to persist across updates we recommend using `local::lib`.
# PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

# pip zsh completion start
_pip_completion() {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip

# Alias to run command with system perl environment: env unset PERL* variables and remove PATH elements with *perl*. macperl perl -V to verify.
alias macperl="env $(print -- '-u '"${(f)^$(env |gi -o "^PERL.*" |cut -d= -f1)}") PATH=$(print -- ${(j%:%)${(s%:%)PATH}:#*perl*}) $*"

# pip zsh completion end

# Lunchy completion integration
alias pip-upgrade-all="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
alias pip3-upgrade-all="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
# pip zsh completion end

# Lunchy completion integration
LUNCHY_DIR=$(dirname `gem which lunchy`)/../extras
  if [ -f $LUNCHY_DIR/lunchy-completion.zsh ]; then
    . $LUNCHY_DIR/lunchy-completion.zsh
  fi

alias pip-upgrade-all='for i ($(awk -v ORS=" " 'NR>2 { print $1 }' <(pip list))) pip install -U "$i" &'
# alias pip-upgrade-all='pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'
alias pip3-upgrade-all='pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U'

# rbenv init (path & completions)
eval "$(rbenv init -)"
if [ -f ${RBENV_DIR:-$HOME/.rbenv} ]; then
  path=("${RBENV_DIR:-$HOME/.rbenv}" "$path[@]")
fi

# added by travis gem
[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

# calculate zshrc load end time
local zshrc_end=$(gdate +%s%N)
function calc () {
  bc -l <<< "$@"
}
if [[ -o login ]]; then
  ZSHRC_LOAD_TIME="~/.zshrc loaded: $(calc "scale=3;($zshrc_end-$zshrc_start)/10^(9)") seconds, IT2 session $TERM_SESSION_ID"
fi
unset zshrc_end
unset zshrc_start
